import tkinter as tk
from tkinter import *

window = tk.Tk()
window.geometry("570x180")
window.attributes("-topmost", True)
window.title("T-Town Veterinary Clinic Database")
window.resizable(False,False)
window.configure(bg="#fff")

dogphoto = PhotoImage(file="dog.png")
label0 = tk.Label(window, image=dogphoto, borderwidth=0)
button1 = tk.Button(window,text="Search by Name", bg="#fff", relief = GROOVE)
entry1 = tk.Entry(window,text="Entry widgets can be typed in", width=23)
Label1 = Label(window,text="Client Database", bg="#fff")
Label2 = Label(window,text="Name", bg="#fff")
Label3 = Label(window,text="Type", bg="#fff")
Label4 = Label(window,text="Breed", bg="#fff")
Label5 = Label(window,text="Owner", bg="#fff")
Label6 = Label(window,text="Birthdate", bg="#fff")
entry2 = tk.Entry(window,text="Entry widgets can be typed in", width=17)
entry3 = tk.Entry(window,text="Entry widgets can be typed in", width=17)
entry4 = tk.Entry(window,text="Entry widgets can be typed in", width=17)
entry5 = tk.Entry(window,text="Entry widgets can be typed in", width=17)
entry6 = tk.Entry(window,text="Entry widgets can be typed in", width=17)
entry7 = tk.Entry(window,text="Entry widgets can be typed in", width=17)
button2 = tk.Button(window,text="Save Entry", relief = GROOVE)
button3 = tk.Button(window,text="< Previous", bg="#fff", relief = GROOVE)
button4 = tk.Button(window,text="Next >", bg="#fff", relief = GROOVE)

label0.grid(row = 1, column = 1, rowspan = 2)
button1.grid(row = 1, column = 4)
entry1.grid(row = 1, column = 5,)
Label1.grid(row = 2, column = 3)
Label2.grid(row = 3, column = 1)
Label3.grid(row = 3, column = 2)
Label4.grid(row = 3, column = 3)
Label5.grid(row = 3, column = 4)
Label6.grid(row = 3, column = 5)
entry2.grid(row = 4, column = 1)
entry3.grid(row = 4, column = 2)
entry4.grid(row = 4, column = 3)
entry5.grid(row = 4, column = 4)
entry6.grid(row = 4, column = 5)
button2.grid(row = 5, column = 3)
button3.grid(row = 5, column = 1)
button4.grid(row = 5, column = 5)

window.mainloop()